stages:
  - build
  - test

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo install cargo-all-features
    - cargo build-all-features --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-all-features
    - cargo build-all-features --verbose
  allow_failure: true
  
rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo install cargo-all-features
    - cargo test-all-features --verbose
    - cargo test --doc
    - cargo test --doc --features uom_units
    
rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-all-features
    - cargo test-all-features --verbose
    - cargo test --doc
    - cargo test --doc --features uom_units
  allow_failure: true