stages:
  - build
  - test

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo build --verbose --features measurements_units

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo build --verbose --features measurements_units
  allow_failure: true
  
rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
    - cargo test --verbose --features measurements_units
    
rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose
    - cargo test --verbose --features measurements_units
  allow_failure: true