[package]
name = "libmedium"
version = "0.1.0"
authors = ["Malte Veerman <malte.veerman@gmail.com>"]
license = "GPL"
description = "Library to interface with lm_sensors"
repository = "https://github.com/Maldela/libmedium"
edition = "2018"

[dependencies]
snafu = "0.6.0"

[lib]
doctest = false

[features]
default = ["writable"]

# Feature that enables the writable versions of all structs and functions to interact with the system's sensors.
writable = []

# Feature that enables parsing of arbitrary paths for hwmons and sensors.
# It should only be needed for debug and testing purposes.
unrestricted_parsing = []